#!/bin/bash

sudo nano ~/.bashrc >> ~/.bashrc
echo ppppp="$(whoami)@$(uname -n)" >> ~/.bashrc
echo lengthofppppp=${#ppppp} >> ~/.bashrc
echo afterppppp="" >> ~/.bashrc
echo clear >> ~/.bashrc

echo echo $ppppp >> ~/.bashrc
echo while [ $lengthofppppp -gt 0 ]; do >> ~/.bashrc
echo   afterppppp+='-' >> ~/.bashrc
echo   lengthofppppp=$((lengthofppppp-1)) >> ~/.bashrc
echo done >> ~/.bashrc

echo echo $afterppppp >> ~/.bashrc
echo echo "OS:             $(uname -o)" >> ~/.bashrc
echo echo "Processor:      $(uname -p)" >> ~/.bashrc
echo echo "Hardware Info:  $(uname -m)" >> ~/.bashrc
echo echo "Kernal Name:    $(uname)" >> ~/.bashrc
echo echo "Kernal Version: $(uname -v)" >> ~/.bashrc
echo echo "Kernal Release: $(uname -r)" >> ~/.bashrc
echo cd >> ~/.bashrc
