#!/bin/bash

echo ${
ppppp="$(whoami)@$(uname -n)"
lengthofppppp=${#ppppp}
afterppppp=""
clear
echo $ppppp
while [ $lengthofppppp -gt 0 ]; do
  afterppppp+=-
  lengthofppppp=$((lengthofppppp-1))
done
echo $afterppppp
echo "OS:             $(uname -o)"
echo "Processor:      $(uname -p)"
echo "Hardware Info:  $(uname -m)"
echo "Kernel Name:    $(uname)"
echo "Kernel Version: $(uname -v)"
echo "Kernel Release: $(uname -r)"
cd
} >> ~/.bashrc
